project_name: go-greeter-user

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch: #Intel and Apple Silicon support
      - amd64
      - arm64

archives:
  - format: tar.gz

checksum:
  name_template: "checksums.txt"

brews:
  - name: greeter-cli
    homepage: https://github.com/abelpenton/go-greeter-user
    description: "A simple CLI to greet users"
    repository:
      owner: abelpenton
      name: homebrew-go-greeter-user
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

publishers:
  - name: npm
    cmd: npx -y goreleaser-npm-publisher publish --clean --token {{ .Env.NPM_TOKEN }}
    dir: "{{ dir .ArtifactPath }}"
    env:
      - NPM_TOKEN={{ .Env.NPM_TOKEN }}
