version: 2

project_name: go-greeter-user

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

brews:
  - name: greeter-cli
    homepage: https://github.com/abelpenton/go-greeter-user
    description: "A simple CLI to greet users"
    repository:
      owner: abelpenton
      name: homebrew-go-greeter-user
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

publishers:
  - name: npm
    cmd: bash scripts/publish-npm.sh
    env:
      - NPM_TOKEN={{ .Env.NPM_TOKEN }}
      - TAG={{ .Tag }}
