project_name: go-greeter-user

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch: #Intel and Apple Silicon support
      - amd64
      - arm64

archives:
  - format: tar.gz

checksum:
  name_template: "checksums.txt"

brews:
  - name: cli
    homepage: https://github.com/abelpenton/go-greeter-user
    description: "A simple CLI to greet users"
    repository:
      owner: abelpenton
      name: homebrew-go-greeter-user
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

nfpms:
  - id: packages
    package_name: go-greeter-user
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "Abel Penton/Organization"
    homepage: "https://github.com/abelpenton/go-greeter-user"
    maintainer: "Abel Penton <2235penton@gmail.com>"
    description: "A simple CLI to greet users"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
    contents:
      - src: "./go-greeter-user"
        dst: "/usr/bin/go-greeter-user"
        mode: "0755"
    contents:
      - src: "./README.md"
        dst: "/usr/share/doc/go-greeter-user/README.md"
