name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload to PackageCloud
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gem install package_cloud

          find dist/ -name "*.deb" -exec package_cloud push abelpenton-dev/abelpenton-dev/ubuntu/focal {} \;
          find dist/ -name "*.deb" -exec package_cloud push abelpenton-dev/abelpenton-dev/debian/bullseye {} \;

          find dist/ -name "*.rpm" -exec package_cloud push abelpenton-dev/abelpenton-dev/el/8 {} \;
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
